# Generated by Django 6.1.2 on 2026-10-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(default='text', max_length=200)),
                ('mark_body', models.CharField(default='text', max_length=1000)),
                ('erased', models.BooleanField(default=False)),
            ],
        ),
    ]
